with open('app/chat/page.tsx', 'r', encoding='utf-8') as f:
    c = f.read()

old = (
    "                    <div\n"
    "                      className={\"chat-bubble max-w-[70%] rounded-2xl px-4 py-3 text-sm leading-relaxed\" + (animatedIds.has(i) ? \" bubble-animate\" : \"\")}\n"
    "                      style={msg.role === 'user'\n"
    "                        ? { background: t.userBubble, color: t.userText, border: `1px solid ${t.userBubbleBorder}`, backdropFilter: 'blur(8px)' }\n"
    "                        : { background: t.assistantBubble, color: t.assistantText, border: `1px solid ${t.assistantBubbleBorder}`, backdropFilter: 'blur(10px)' }\n"
    "                      }\n"
    "                    >\n"
    "                      {msg.role === 'user' ? msg.content : (\n"
    "                        <ReactMarkdown\n"
    "                          components={{\n"
    "                            p: ({ children }) => <p className=\"mb-2 last:mb-0\">{children}</p>,\n"
    "                            code: ({ children, className }) => {\n"
    "                              const isBlock = className?.includes('language-')\n"
    "                              const language = className?.replace('language-', '') ?? 'text'\n"
    "                              if (isBlock) {\n"
    "                                const { Prism: SyntaxHighlighter } = require('react-syntax-highlighter')\n"
    "                                const { oneDark } = require('react-syntax-highlighter/dist/cjs/styles/prism')\n"
    "                                return (\n"
    "                                  <SyntaxHighlighter\n"
    "                                    language={language}\n"
    "                                    style={oneDark}\n"
    "                                    customStyle={{ borderRadius: '8px', fontSize: '12px', margin: '8px 0', background: t.codeBg }}\n"
    "                                  >\n"
    "                                    {String(children).replace(/\\n$/, '')}\n"
    "                                  </SyntaxHighlighter>\n"
    "                                )\n"
    "                              }\n"
    "                              return (\n"
    "                                <code className=\"rounded px-1 py-0.5 text-xs\" style={{ background: t.codeBg, color: t.codeText }}>{children}</code>\n"
    "                              )\n"
    "                            },\n"
    "                            ul: ({ children }) => <ul className=\"list-disc pl-4 mb-2 space-y-1\">{children}</ul>,\n"
    "                            ol: ({ children }) => <ol className=\"list-decimal pl-4 mb-2 space-y-1\">{children}</ol>,\n"
    "                            li: ({ children }) => <li>{children}</li>,\n"
    "                            strong: ({ children }) => <strong className=\"font-semibold\" style={{ color: t.strongText }}>{children}</strong>,\n"
    "                            h1: ({ children }) => <h1 className=\"text-base font-semibold mb-2\" style={{ color: t.strongText }}>{children}</h1>,\n"
    "                            h2: ({ children }) => <h2 className=\"text-sm font-semibold mb-2\" style={{ color: t.strongText }}>{children}</h2>,\n"
    "                            h3: ({ children }) => <h3 className=\"text-sm font-semibold mb-1\" style={{ color: t.strongText }}>{children}</h3>,\n"
    "                          }}\n"
    "                        >\n"
    "                          {msg.content.startsWith('<think>') && !msg.content.includes('</think>') ? '' : msg.content.replace(/^<think>[\\s\\S]*?<\\/think>\\n?/, '')}\n"
    "                        </ReactMarkdown>\n"
    "                      )}\n"
    "                    </div>"
)

new = (
    "                    {msg.role === 'user' ? (\n"
    "                      <div\n"
    "                        className={\"chat-bubble max-w-[70%] rounded-2xl px-4 py-3 text-sm leading-relaxed\" + (animatedIds.has(i) ? \" bubble-animate\" : \"\")}\n"
    "                        style={{ background: t.userBubble, color: t.userText, border: `1px solid ${t.userBubbleBorder}`, backdropFilter: 'blur(8px)' }}\n"
    "                      >\n"
    "                        {msg.content}\n"
    "                      </div>\n"
    "                    ) : (() => {\n"
    "                      const cleanContent = msg.content.startsWith('<think>') && !msg.content.includes('</think>') ? '' : msg.content.replace(/^<think>[\\s\\S]*?<\\/think>\\n?/, '')\n"
    "                      const rawSegments = cleanContent.split(/\\n\\n+/).filter(s => s.trim())\n"
    "                      const segments = rawSegments.length === 0 ? [''] : rawSegments\n"
    "                      return (\n"
    "                        <>\n"
    "                          {segments.map((seg, si) => (\n"
    "                            <div\n"
    "                              key={si}\n"
    "                              className={\"chat-bubble max-w-[70%] rounded-2xl px-4 py-3 text-sm leading-relaxed\" + (animatedIds.has(i) ? \" bubble-animate\" : \"\") + (si < segments.length - 1 ? \" mb-1\" : \"\")}\n"
    "                              style={{ background: t.assistantBubble, color: t.assistantText, border: `1px solid ${t.assistantBubbleBorder}`, backdropFilter: 'blur(10px)' }}\n"
    "                            >\n"
    "                              <ReactMarkdown\n"
    "                                components={{\n"
    "                                  p: ({ children }) => <p className=\"mb-2 last:mb-0\">{children}</p>,\n"
    "                                  code: ({ children, className }) => {\n"
    "                                    const isBlock = className?.includes('language-')\n"
    "                                    const language = className?.replace('language-', '') ?? 'text'\n"
    "                                    if (isBlock) {\n"
    "                                      const { Prism: SyntaxHighlighter } = require('react-syntax-highlighter')\n"
    "                                      const { oneDark } = require('react-syntax-highlighter/dist/cjs/styles/prism')\n"
    "                                      return (\n"
    "                                        <SyntaxHighlighter\n"
    "                                          language={language}\n"
    "                                          style={oneDark}\n"
    "                                          customStyle={{ borderRadius: '8px', fontSize: '12px', margin: '8px 0', background: t.codeBg }}\n"
    "                                        >\n"
    "                                          {String(children).replace(/\\n$/, '')}\n"
    "                                        </SyntaxHighlighter>\n"
    "                                      )\n"
    "                                    }\n"
    "                                    return (\n"
    "                                      <code className=\"rounded px-1 py-0.5 text-xs\" style={{ background: t.codeBg, color: t.codeText }}>{children}</code>\n"
    "                                    )\n"
    "                                  },\n"
    "                                  ul: ({ children }) => <ul className=\"list-disc pl-4 mb-2 space-y-1\">{children}</ul>,\n"
    "                                  ol: ({ children }) => <ol className=\"list-decimal pl-4 mb-2 space-y-1\">{children}</ol>,\n"
    "                                  li: ({ children }) => <li>{children}</li>,\n"
    "                                  strong: ({ children }) => <strong className=\"font-semibold\" style={{ color: t.strongText }}>{children}</strong>,\n"
    "                                  h1: ({ children }) => <h1 className=\"text-base font-semibold mb-2\" style={{ color: t.strongText }}>{children}</h1>,\n"
    "                                  h2: ({ children }) => <h2 className=\"text-sm font-semibold mb-2\" style={{ color: t.strongText }}>{children}</h2>,\n"
    "                                  h3: ({ children }) => <h3 className=\"text-sm font-semibold mb-1\" style={{ color: t.strongText }}>{children}</h3>,\n"
    "                                }}\n"
    "                              >\n"
    "                                {seg}\n"
    "                              </ReactMarkdown>\n"
    "                            </div>\n"
    "                          ))}\n"
    "                        </>\n"
    "                      )\n"
    "                    })()}"
)

print('找到：' + str(old in c))
if old in c:
    c = c.replace(old, new)
    print('替换成功')
with open('app/chat/page.tsx', 'w', encoding='utf-8') as f:
    f.write(c)
